openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/bapz/id:
    post:
      summary: Get product details by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  found:
                    type: string
                  src:
                    type: array
                    items:
                      type: string
                  data:
                    type: object
      tags:
        - Product
