openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: This is a sample API
servers:
  - url: http://localhost:3000
paths:
  /hello:
    get:
      summary: Say hello
      responses:
        '200':
          description: A successful response
